name: onnx converter

#  h2oai/deberta_finetuned_pii

on:
    workflow_dispatch:

jobs:
    export_onnx:
        runs-on: ubuntu-latest
        
        steps:
            - name: Install dependencies
              run: | 
                pip install optimum[onnxruntime]
                pip install transformers
            
            - name: Export model to onnx
              run: |
                optimum-cli export onnx \
                 -m h2oai/deberta_finetuned_pii \
                 --task text-classification \
                 h2oai_deberta_finetuned_pii
            
            - name: Upload locally
              uses: actions/upload-artifact@v4
              with:
                name: h2oai_deberta_finetuned_pii.onnx
                path: h2oai_deberta_finetuned_pii
